version: '2.3'

services:
  bash:
    build:
      context: ../.
      dockerfile: ./docker/cpu/Dockerfile
      network: host
    image: tf-unet-cpu
    command: bash
    volumes:
      - '../.:/app/src'
      - '/srv:/srv'
      - '/mnt:/mnt'
    ports: ["${TBPORT:-6056}:6006", "${JNPORT:-6059}:8888", "${PDPORT:-6058}:6058"]

  bash-gpu:
    build:
      context: ../.
      dockerfile: ./docker/gpu/Dockerfile
      network: host
    image: tf-unet-gpu
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: bash  
    volumes:
      - '../.:/app/src'
      - '/srv:/srv'
      - '/mnt:/mnt'
    ports: ["${TBPORT:-6056}:6006", "${JNPORT:-6059}:8888", "${PDPORT:-6058}:6058"]
